/**
 * @picompanion/design-tokens — token source of truth (plan.md §10.2).
 *
 * This module owns every raw value (hex colors, pixel numbers, durations)
 * used by the product. Nothing outside this file should contain a raw hex
 * literal, a raw pixel spacing number, or a raw motion duration: web
 * consumers use the CSS custom properties generated by `web.ts`, and
 * Android consumers use the typed theme objects generated by `native.ts`.
 *
 * T13B (plan §10.2, docs/issues-from-plan.md "Phase 3.5") retokened this
 * file to Beautiful UI's (https://www.beautifului.dev/) semantic structure
 * and published values, recorded in `docs/beautiful-ui-reference.md`. T13C
 * (docs/issues-from-plan.md, same phase) then replaced every value T13B had
 * approximated with the published figure once the reference document's
 * light-theme table was completed: every color role and shadow string
 * below, both themes, is now an extracted published value, not an
 * approximation. Only *values* are adapted here, not code, so no
 * `THIRD_PARTY_NOTICES.md` row is required (see its §2 "Purely visual
 * conformance ... does not require a row").
 *
 * The pre-T13B semantic role names (`background`, `surface`, `textPrimary`,
 * ...) are kept as compatibility aliases pointing at the new Beautiful
 * UI-named fields so existing call sites keep compiling; T25C/T26C migrate
 * components to the new names directly and may remove the aliases once no
 * call site references them.
 *
 * T54A1 (docs/issues-from-plan.md, docs/beautiful-ui-reference.md "WCAG AA
 * contrast pass") deliberately deviates several of the values above from
 * Beautiful UI's byte-exact published figures: a real-browser axe run found
 * the published palette fails WCAG AA (4.5:1) for ordinary text in both
 * themes, not only for the handful of pairs that page happened to render.
 * Per user decision 2026-09-03, accessibility wins over byte-exact fidelity.
 * Every nudge is minimal (same hue, adjusted lightness only), verified with
 * the standard WCAG relative-luminance contrast formula against every
 * background the color is actually painted on (`page`/`canvas`/`surface`/
 * `inset`, and each tone's own tint where it is used as chip/toast text),
 * and recorded with before/after ratios in `docs/beautiful-ui-reference.md`
 * "WCAG AA contrast pass (T54A1)". `packages/design-tokens/src/tokens.test.ts`
 * asserts every ratio programmatically so the palette cannot silently regress
 * below AA again.
 */

// ---------------------------------------------------------------------------
// Color palette (private) — never exported directly. All product code must
// go through the semantic roles in `ColorTokens` / `ThemeTokens` instead.
// ---------------------------------------------------------------------------

/**
 * Beautiful UI's dark theme (the library default). Values are the exact hex
 * figures published in `docs/beautiful-ui-reference.md`'s dark-theme table;
 * `*-tint` roles are the documented alpha overlays (accent/green/orange/red
 * at 16%/14%/14%/14% of their own hue), `stripe` is white at 5.5% alpha, and
 * `tooltip-fg`/`tooltip-muted`/`tooltip-border`/`stripe-bg` (T13C) are the
 * remaining published dark-theme roles that T13B had not yet carried.
 *
 * T54A1 nudges three roles off the published figure to clear WCAG AA (see
 * the file header and `docs/beautiful-ui-reference.md` "WCAG AA contrast
 * pass (T54A1)" for the measured before/after ratios): `ink-3` is lightened
 * (it fell as low as 3.08:1 as text against `surface`), `accent` is
 * lightened slightly (its own 16%-alpha tint composited over `surface`
 * fell to 4.20:1), and `red` is lightened slightly for the same reason
 * (composited red-tint over `surface` fell to 3.93:1). `green` and
 * `orange` already cleared AA everywhere they are used and are unchanged.
 */
const beautifulDark = {
  page: "#17181a",
  canvas: "#1c1d1f",
  surface: "#232427",
  inset: "#1f2022",
  hover: "#2a2b2e",
  "hover-2": "#313236",
  field: "#2b2c2f",
  ink: "#f2f3f4",
  "ink-2": "#a5a8ad",
  // T54A1: was #6c6f75 (3.08:1 as text on `surface`, needs 4.5:1). See
  // docs/beautiful-ui-reference.md "WCAG AA contrast pass (T54A1)". The
  // first pass stopped at #878b91, which cleared the content backdrops but
  // only reached 4.08:1 on `field` and 4.13:1 on `hover` -- and the Android
  // text primitives really do paint this role as placeholder text on
  // `field` (TextField.tsx:34, TextArea.tsx:28, SearchField.tsx:25,
  // CommandSearch.tsx:66, PromptBar.tsx:49). #92959b clears every backdrop
  // this role is painted on, worst case 4.65:1 on `field`.
  "ink-3": "#92959b",
  line: "#2e3033",
  "line-strong": "#3a3c40",
  "line-soft": "#27282b",
  // T54A1: was #3d9aff (its 16%-alpha tint, composited over `surface`,
  // gave 4.20:1 as chip/toast text, needs 4.5:1).
  accent: "#4da3ff",
  "accent-ink": "#7ec0ff",
  "accent-tint": "rgba(61, 154, 255, 0.16)",
  green: "#3cbb72",
  orange: "#f68f3c",
  // T54A1: was #ee5c61 (its 14%-alpha tint, composited over `surface`,
  // gave 3.93:1 as chip/toast text, needs 4.5:1).
  red: "#f17579",
  "green-tint": "rgba(60, 187, 114, 0.14)",
  "orange-tint": "rgba(246, 143, 60, 0.14)",
  "red-tint": "rgba(238, 92, 97, 0.14)",
  "tooltip-bg": "#111214",
  "tooltip-fg": "#f2f3f4",
  "tooltip-muted": "#a5a8ad",
  "tooltip-border": "#2e3033",
  stripe: "rgba(255, 255, 255, 0.055)",
  "stripe-bg": "#1b1c1e",
} as const;

/**
 * Beautiful UI's light theme (T13C, docs/beautiful-ui-reference.md "Light
 * theme" table). Every role below is now an extracted published value: the
 * reference document previously omitted `hover`/`hover-2`/`accent-ink`/the
 * tint roles/`tooltip-*`/`stripe`/`stripe-bg` and those were approximated by
 * T13B; the table now publishes all of them and this file carries the
 * published figures exactly. Per the reference's structural note, light
 * tints (`accent-tint`, `*-tint`) are near-white **solid** fills, not alpha
 * overlays of the dark theme's tint hue — do not mechanically mirror
 * `beautifulDark`'s tint construction here.
 *
 * T54A1 darkens six roles off the published figure to clear WCAG AA (see
 * the file header and `docs/beautiful-ui-reference.md` "WCAG AA contrast
 * pass (T54A1)" for the measured before/after ratios): a real-browser axe
 * run found `ink-3` at 2.61-2.72:1 as text, and `accent`/`accent-ink`/
 * `green`/`orange`/`red` all failed 4.5:1 both as direct text (e.g. field
 * error labels, links) and as foreground-on-their-own-tint text (chips,
 * toasts) once every pair actually used was audited, not only the ones
 * axe happened to render. Every nudge keeps the same hue and saturation,
 * lightness only, chosen as the minimal darkening that clears the worst
 * background each color is actually painted behind (`canvas` for most
 * roles; each tone's own near-white tint for `red`, which is very slightly
 * darker than `canvas`).
 */
const beautifulLight = {
  page: "#fafafb",
  canvas: "#f1f2f3",
  surface: "#ffffff",
  inset: "#f7f8f9",
  hover: "#f4f5f6",
  "hover-2": "#e7e9eb",
  field: "#f2f2f3",
  ink: "#1f2124",
  "ink-2": "#62656b",
  // T54A1: was #9a9da3 (2.61:1 on `page`, 2.72:1 on `surface`; needs 4.5:1).
  "ink-3": "#6b6f76",
  line: "#ecedef",
  "line-strong": "#e0e2e5",
  "line-soft": "#f3f4f5",
  // T54A1: was #0285ff (3.62:1 as text/as the primary button's background
  // under white text; needs 4.5:1 both ways — this is Beautiful UI's
  // published `accent`, symmetric with the earlier "white on light accent
  // 3.62:1" axe finding).
  accent: "#006dd3",
  // T54A1: was #0070dd (4.30:1 as link-hover text on `canvas`; needs
  // 4.5:1). Darkened further than `accent` to preserve the original hover
  // ramp's relative darkness.
  "accent-ink": "#005aaf",
  "accent-tint": "#e9f3ff",
  // T54A1: was #199a4d (3.25:1 as text on `canvas`; needs 4.5:1).
  green: "#157f40",
  // T54A1: was #ef720d (2.65:1 as text on `canvas`; needs 4.5:1).
  orange: "#b1540a",
  // T54A1: was #e3474c (3.98:1 as white-on-red button text, 3.48:1 as
  // red-on-red-tint chip text; needs 4.5:1). `red-tint` (below) is the
  // binding constraint, very slightly darker than `canvas`.
  red: "#d52026",
  "green-tint": "#e8f5ed",
  "orange-tint": "#fdf1e5",
  "red-tint": "#fcecec",
  "tooltip-bg": "#25272b",
  "tooltip-fg": "#f6f7f8",
  "tooltip-muted": "#a5a8ad",
  "tooltip-border": "#3a3c40",
  // Published as `oklch(40.5% 0 0/.075)` ("grey @7.5%", no hex column in
  // the reference); the achromatic OKLab->sRGB conversion is rgb(73, 73,
  // 73), i.e. #494949 at 7.5% alpha.
  stripe: "rgba(73, 73, 73, 0.075)",
  "stripe-bg": "#f5f5f5",
} as const;

// ---------------------------------------------------------------------------
// Semantic color roles
// ---------------------------------------------------------------------------

/** Beautiful UI's surface stack (plan §10.2): `page → canvas → surface → inset → field`. */
export interface SurfaceColorTokens {
  page: string;
  canvas: string;
  surface: string;
  inset: string;
  hover: string;
  "hover-2": string;
  field: string;
}

/** Beautiful UI's text ramp: `ink → ink-2 → ink-3`. */
export interface TextColorRamp {
  ink: string;
  "ink-2": string;
  "ink-3": string;
}

/** Beautiful UI's hairline family: `line` / `line-strong` / `line-soft`. */
export interface LineColorTokens {
  line: string;
  "line-strong": string;
  "line-soft": string;
}

/** Beautiful UI's accent tone with its text and tint variants. */
export interface AccentColorTokens {
  accent: string;
  "accent-ink": string;
  "accent-tint": string;
}

/** Beautiful UI's status tones (green/orange/red) with their tints. */
export interface ToneColorTokens {
  green: string;
  orange: string;
  red: string;
  "green-tint": string;
  "orange-tint": string;
  "red-tint": string;
}

/** Miscellaneous Beautiful UI roles that don't belong to another group. */
export interface MiscBeautifulColorTokens {
  "tooltip-bg": string;
  "tooltip-fg": string;
  "tooltip-muted": string;
  "tooltip-border": string;
  stripe: string;
  "stripe-bg": string;
}

export interface SemanticColorTokens
  extends
    SurfaceColorTokens,
    TextColorRamp,
    LineColorTokens,
    AccentColorTokens,
    ToneColorTokens,
    MiscBeautifulColorTokens {
  // ---- Legacy roles (pre-T13B) -------------------------------------------
  // Kept as compatibility aliases pointing at the Beautiful UI-named fields
  // above so existing call sites keep compiling after the T13B retoken.
  // New code should prefer the fields above; T25C/T26C may remove these
  // once no call site references them (docs/issues-from-plan.md T13B).
  background: string;
  backgroundElevated: string;
  surfaceRaised: string;
  surfaceOverlay: string;
  border: string;
  borderStrong: string;
  borderFocus: string;
  textPrimary: string;
  textSecondary: string;
  textTertiary: string;
  textDisabled: string;
  textInverse: string;
  accentHover: string;
  accentActive: string;
  accentMuted: string;
  accentContrast: string;
  link: string;
  linkHover: string;
  focusRing: string;
  overlayScrim: string;
}

export interface StatusTone {
  foreground: string;
  background: string;
  border: string;
  icon: string;
}

export interface StatusTones {
  success: StatusTone;
  warning: StatusTone;
  danger: StatusTone;
  info: StatusTone;
  neutral: StatusTone;
}

export interface SyntaxColors {
  keyword: string;
  string: string;
  comment: string;
  function: string;
  number: string;
  type: string;
  variable: string;
  operator: string;
  punctuation: string;
}

export interface CodeDiffColors {
  codeBackground: string;
  codeForeground: string;
  codeBorder: string;
  diffAddedBackground: string;
  diffAddedForeground: string;
  diffAddedBorder: string;
  diffRemovedBackground: string;
  diffRemovedForeground: string;
  diffRemovedBorder: string;
  diffModifiedBackground: string;
  diffModifiedForeground: string;
  diffModifiedBorder: string;
  syntax: SyntaxColors;
}

export interface ColorTokens extends SemanticColorTokens {
  status: StatusTones;
  code: CodeDiffColors;
}

/**
 * Text painted directly on a saturated solid accent/status fill (e.g. the
 * primary button's `accent` background, or Android's solid `danger`
 * button) — the fill's own color, not the surrounding theme, sets the
 * required contrast direction.
 *
 * T54A1: this used to be a single near-white constant for both themes,
 * which passed in the light theme (where `accent`/`red` are now dark
 * enough, per the darkening above, for near-white text to reach 4.5:1) but
 * failed badly in the dark theme, where `accent`/`red`/`green`/`orange` are
 * themselves light, saturated colors close in luminance to near-white text
 * (measured 2.72:1 white-on-accent, 3.12:1 white-on-red — see
 * docs/beautiful-ui-reference.md "WCAG AA contrast pass (T54A1)"). Rather
 * than darken the dark theme's already-passing accent/status hues further
 * (which would fight the lightening those same roles needed for their own
 * alpha-tint chip/toast text above), the dark theme pairs its solid fills
 * with dark text instead: `beautifulDark.page` reaches 5.4-7.5:1 against
 * every solid fill color in this file, comfortably clearing 4.5:1 without
 * moving the fills at all.
 */
function onSolidFillFor(p: typeof beautifulDark | typeof beautifulLight): string {
  return p === beautifulDark ? beautifulDark.page : "#f7f8f9";
}

function buildColors(p: typeof beautifulDark | typeof beautifulLight): ColorTokens {
  const onSolidFill = onSolidFillFor(p);
  return {
    // Beautiful UI-named fields, verbatim from the palette above.
    page: p.page,
    canvas: p.canvas,
    surface: p.surface,
    inset: p.inset,
    hover: p.hover,
    "hover-2": p["hover-2"],
    field: p.field,
    ink: p.ink,
    "ink-2": p["ink-2"],
    "ink-3": p["ink-3"],
    line: p.line,
    "line-strong": p["line-strong"],
    "line-soft": p["line-soft"],
    accent: p.accent,
    "accent-ink": p["accent-ink"],
    "accent-tint": p["accent-tint"],
    green: p.green,
    orange: p.orange,
    red: p.red,
    "green-tint": p["green-tint"],
    "orange-tint": p["orange-tint"],
    "red-tint": p["red-tint"],
    "tooltip-bg": p["tooltip-bg"],
    "tooltip-fg": p["tooltip-fg"],
    "tooltip-muted": p["tooltip-muted"],
    "tooltip-border": p["tooltip-border"],
    stripe: p.stripe,
    "stripe-bg": p["stripe-bg"],

    // Legacy aliases, mapped onto the fields above.
    background: p.page,
    backgroundElevated: p.canvas,
    surfaceRaised: p.hover,
    surfaceOverlay: p["hover-2"],
    border: p.line,
    borderStrong: p["line-strong"],
    borderFocus: p.accent,
    textPrimary: p.ink,
    textSecondary: p["ink-2"],
    textTertiary: p["ink-3"],
    textDisabled: p["ink-3"],
    // T54A1: theme-conditional, see `onSolidFillFor` above.
    textInverse: onSolidFill,
    accentHover: p["accent-ink"],
    accentActive: p["accent-ink"],
    accentMuted: p["accent-tint"],
    accentContrast: onSolidFill,
    link: p.accent,
    linkHover: p["accent-ink"],
    focusRing: p.accent,
    overlayScrim: p === beautifulDark ? "rgba(17, 18, 20, 0.72)" : "rgba(31, 33, 36, 0.48)",

    status: {
      success: { foreground: p.green, background: p["green-tint"], border: p.green, icon: p.green },
      warning: {
        foreground: p.orange,
        background: p["orange-tint"],
        border: p.orange,
        icon: p.orange,
      },
      danger: { foreground: p.red, background: p["red-tint"], border: p.red, icon: p.red },
      info: {
        foreground: p.accent,
        background: p["accent-tint"],
        border: p.accent,
        icon: p.accent,
      },
      neutral: { foreground: p["ink-2"], background: p.inset, border: p.line, icon: p["ink-3"] },
    },
    code: {
      codeBackground: p.inset,
      codeForeground: p.ink,
      codeBorder: p.line,
      diffAddedBackground: p["green-tint"],
      diffAddedForeground: p.green,
      diffAddedBorder: p.green,
      diffRemovedBackground: p["red-tint"],
      diffRemovedForeground: p.red,
      diffRemovedBorder: p.red,
      diffModifiedBackground: p["orange-tint"],
      diffModifiedForeground: p.orange,
      diffModifiedBorder: p.orange,
      // Beautiful UI doesn't publish a syntax-highlighting palette; this
      // reuses its ink ramp plus the accent/tone colors it does publish.
      syntax: {
        keyword: p["accent-ink"],
        string: p.green,
        comment: p["ink-3"],
        function: p.accent,
        number: p.orange,
        type: p["accent-ink"],
        variable: p.ink,
        operator: p["ink-2"],
        punctuation: p["ink-3"],
      },
    },
  };
}

const lightColors: ColorTokens = buildColors(beautifulLight);
const darkColors: ColorTokens = buildColors(beautifulDark);

// High-contrast variants raise text/border contrast against the background
// and remove partial-opacity fills, per plan §10.5 ("Test ... high
// contrast").
function boostStatusForHighContrast(status: StatusTones, solidBackground: string): StatusTones {
  const boost = (tone: StatusTone): StatusTone => ({ ...tone, background: solidBackground });
  return {
    success: boost(status.success),
    warning: boost(status.warning),
    danger: boost(status.danger),
    info: boost(status.info),
    neutral: boost(status.neutral),
  };
}

const lightHighContrastColors: ColorTokens = {
  ...lightColors,
  ink: "#000000",
  "ink-2": "#1f2124",
  "ink-3": "#62656b",
  line: "#62656b",
  "line-strong": "#000000",
  textPrimary: "#000000",
  textSecondary: "#1f2124",
  textTertiary: "#62656b",
  border: "#62656b",
  borderStrong: "#000000",
  borderFocus: "#000000",
  focusRing: "#000000",
  status: boostStatusForHighContrast(lightColors.status, beautifulLight.surface),
};

const darkHighContrastColors: ColorTokens = {
  ...darkColors,
  ink: "#ffffff",
  "ink-2": "#f2f3f4",
  "ink-3": "#a5a8ad",
  line: "#a5a8ad",
  "line-strong": "#ffffff",
  textPrimary: "#ffffff",
  textSecondary: "#f2f3f4",
  textTertiary: "#a5a8ad",
  border: "#a5a8ad",
  borderStrong: "#ffffff",
  borderFocus: "#ffffff",
  focusRing: "#ffffff",
  status: boostStatusForHighContrast(darkColors.status, beautifulDark.canvas),
};

// ---------------------------------------------------------------------------
// Shadows — Beautiful UI's ring-based shadow set (plan §10.2: "1px rings,
// not blurs"). `hairline` is the workhorse (`0 0 0 1px` the theme's line
// color). T13C (docs/beautiful-ui-reference.md "Shape, shadow, type,
// motion") carries every published shadow string for both themes, including
// `raised` (previously missing entirely) and the corrected light-theme set:
// dark values are the reference's literal strings; light values compose the
// reference's own formulas — `0 0 0 1px var(--line|--line-strong)` plus
// Tailwind's well-known default `--shadow-xs/sm/md/lg` blur scale, exactly
// as the reference's "Light composes the same ring with Tailwind's default
// blur scale" note specifies.
// ---------------------------------------------------------------------------

export interface ShadowTokens {
  hairline: string;
  btn: string;
  card: string;
  raised: string;
  overlay: string;
  insetField: string;
}

const darkShadows: ShadowTokens = {
  hairline: `0 0 0 1px ${beautifulDark.line}`,
  btn: "0 0 0 1px rgba(255, 255, 255, 0.1), 0 1px 2px rgba(0, 0, 0, 0.3)",
  card: "0 0 0 1px rgba(255, 255, 255, 0.11), 0 1px 2px rgba(0, 0, 0, 0.2), 0 2px 6px rgba(0, 0, 0, 0.2)",
  raised: "0 0 0 1px rgba(255, 255, 255, 0.13), 0 2px 10px rgba(0, 0, 0, 0.22)",
  overlay: "0 0 0 1px rgba(255, 255, 255, 0.15), 0 8px 28px rgba(0, 0, 0, 0.34)",
  insetField: "inset 0 1px 2px rgba(0, 0, 0, 0.4)",
};

const lightShadows: ShadowTokens = {
  hairline: `0 0 0 1px ${beautifulLight.line}`,
  // ring: var(--line-strong) + Tailwind --shadow-xs: 0 1px 2px 0 rgb(0 0 0/.05)
  btn: `0 0 0 1px ${beautifulLight["line-strong"]}, 0 1px 2px rgba(0, 0, 0, 0.05)`,
  // ring: var(--line) + Tailwind --shadow-sm: 0 1px 3px 0 + 0 1px 2px -1px, both @.1
  card: `0 0 0 1px ${beautifulLight.line}, 0 1px 3px rgba(0, 0, 0, 0.1), 0 1px 2px -1px rgba(0, 0, 0, 0.1)`,
  // ring: var(--line) + Tailwind --shadow-md: 0 4px 6px -1px + 0 2px 4px -2px, both @.1
  raised: `0 0 0 1px ${beautifulLight.line}, 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1)`,
  // ring: var(--line) + Tailwind --shadow-lg: 0 10px 15px -3px + 0 4px 6px -4px, both @.1
  overlay: `0 0 0 1px ${beautifulLight.line}, 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -4px rgba(0, 0, 0, 0.1)`,
  insetField: "inset 0 1px 2px rgba(0, 0, 0, 0.12)",
};

// ---------------------------------------------------------------------------
// Typography
// ---------------------------------------------------------------------------

export interface TypographyTokens {
  fontFamily: {
    sans: string;
    mono: string;
  };
  fontSize: {
    xs: number;
    sm: number;
    md: number;
    base: number;
    lg: number;
    xl: number;
    "2xl": number;
    "3xl": number;
    "4xl": number;
  };
  fontWeight: {
    regular: number;
    medium: number;
    semibold: number;
    bold: number;
  };
  lineHeight: {
    tight: number;
    snug: number;
    normal: number;
    relaxed: number;
  };
  letterSpacing: {
    tight: number;
    normal: number;
    wide: number;
  };
}

/**
 * Beautiful UI's type scale (plan §10.2): small sizes dominate (10.5-13px),
 * section titles sit at 13px/600, and the page heading is 21px/600 with
 * `tracking-[-0.02em]`. Mapped onto the existing named scale so call sites
 * keep compiling: `xs`..`base` cover the dominant small range, `lg` is the
 * 13px section-title size, and `4xl` is the 21px page heading.
 */
export const typography: TypographyTokens = {
  fontFamily: {
    sans: '"Inter", -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
    mono: '"Geist Mono", "SF Mono", Menlo, Consolas, monospace',
  },
  fontSize: {
    xs: 10.5,
    sm: 11,
    md: 11.5,
    base: 12.5,
    lg: 13,
    xl: 15,
    "2xl": 17,
    "3xl": 19,
    "4xl": 21,
  },
  fontWeight: {
    regular: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
  },
  lineHeight: {
    tight: 1.2,
    snug: 1.35,
    // Beautiful UI: "Body line-height relaxed (1.625)".
    normal: 1.5,
    relaxed: 1.625,
  },
  letterSpacing: {
    // Beautiful UI: page heading tracking is `-0.02em`.
    tight: -0.02,
    normal: 0,
    wide: 0.02,
  },
};

/**
 * T13C (docs/issues-from-plan.md "Bundle Inter/Geist Mono and complete
 * light-theme values"): the exact font-family names the bundled font files
 * are registered under on each platform. This is the single source of
 * truth both `native.ts` (which resolves a theme's `fontFamily` to one of
 * these names, per weight) and `apps/android`'s `expo-font` loader (which
 * must register its `require()`d TTFs under these same keys) read from, so
 * the two can never drift out of sync the way the CSS-stack string alone
 * did before T13C (a family name that isn't actually registered fails
 * silently on Android, falling back to a system face).
 *
 * Web does not need a per-weight map: `@font-face` declarations select the
 * right file by `font-weight` for a single family name ("Inter" / "Geist
 * Mono", the first entry in each `typography.fontFamily` stack above), the
 * way browsers have always resolved custom fonts.
 */
export const nativeFontFamilyNames = {
  sans: {
    regular: "Inter_400Regular",
    medium: "Inter_500Medium",
    semibold: "Inter_600SemiBold",
    bold: "Inter_700Bold",
  },
  mono: {
    regular: "GeistMono_400Regular",
    medium: "GeistMono_500Medium",
    semibold: "GeistMono_600SemiBold",
    bold: "GeistMono_700Bold",
  },
} as const;

export type NativeFontWeightKey = keyof TypographyTokens["fontWeight"];

// ---------------------------------------------------------------------------
// Spacing and radii
// ---------------------------------------------------------------------------

export interface SpacingTokens {
  0: number;
  1: number;
  2: number;
  3: number;
  4: number;
  5: number;
  6: number;
  8: number;
  10: number;
  12: number;
  16: number;
  20: number;
  24: number;
}

export const spacing: SpacingTokens = {
  0: 0,
  1: 4,
  2: 8,
  3: 12,
  4: 16,
  5: 20,
  6: 24,
  8: 32,
  10: 40,
  12: 48,
  16: 64,
  20: 80,
  24: 96,
};

export interface RadiiTokens {
  none: number;
  sm: number;
  md: number;
  lg: number;
  xl: number;
  full: number;
  /** Beautiful UI's named radii (plan §10.2), aliasing sm/md/lg/xl above. */
  chip: number;
  control: number;
  card: number;
  window: number;
}

// Beautiful UI radii (plan §10.2): chip 6 / control 8 / card 10 / window 14,
// pills fully round.
export const radii: RadiiTokens = {
  none: 0,
  sm: 6,
  md: 8,
  lg: 10,
  xl: 14,
  full: 9999,
  chip: 6,
  control: 8,
  card: 10,
  window: 14,
};

// ---------------------------------------------------------------------------
// Elevation (theme-independent shadow/border rules)
// ---------------------------------------------------------------------------

export interface ElevationLevel {
  /** Vertical shadow offset in density-independent pixels. */
  offsetY: number;
  /** Gaussian blur radius in density-independent pixels. */
  blurRadius: number;
  /** Shadow opacity, 0-1, against a black shadow color. */
  opacity: number;
  /** Android `elevation` prop value (dp). */
  androidElevation: number;
}

export interface ElevationTokens {
  0: ElevationLevel;
  1: ElevationLevel;
  2: ElevationLevel;
  3: ElevationLevel;
  4: ElevationLevel;
}

/**
 * Legacy single-layer shadow model, retained for `theme.elevation[n]`
 * (Android `NativeShadow`) and `--elevation-n` (web) call sites. Retuned to
 * Beautiful UI's tighter, more restrained magnitude (plan §10.2); the real
 * ring-based shadow set is `ShadowTokens` (`theme.shadows`) above, which
 * T25C/T26C should prefer.
 */
export const elevation: ElevationTokens = {
  0: { offsetY: 0, blurRadius: 0, opacity: 0, androidElevation: 0 },
  1: { offsetY: 1, blurRadius: 2, opacity: 0.3, androidElevation: 1 },
  2: { offsetY: 1, blurRadius: 3, opacity: 0.2, androidElevation: 2 },
  3: { offsetY: 2, blurRadius: 6, opacity: 0.2, androidElevation: 4 },
  4: { offsetY: 8, blurRadius: 28, opacity: 0.34, androidElevation: 8 },
};

// ---------------------------------------------------------------------------
// Motion
// ---------------------------------------------------------------------------

export interface MotionDurations {
  instant: number;
  fast: number;
  base: number;
  moderate: number;
  slow: number;
  slower: number;
  /** Beautiful UI's `fade-up` section-entrance duration. */
  entrance: number;
}

export interface MotionEasing {
  standard: [number, number, number, number];
  decelerate: [number, number, number, number];
  accelerate: [number, number, number, number];
  sharp: [number, number, number, number];
  /** Beautiful UI's signature easing, `cubic-bezier(.23,1,.32,1)`. */
  easeOutStrong: [number, number, number, number];
  /** Beautiful UI's exit/collapse easing, `cubic-bezier(.77,0,.175,1)`. */
  easeInOutStrong: [number, number, number, number];
  /** Beautiful UI's link-underline easing, `cubic-bezier(.16,1,.3,1)`. */
  link: [number, number, number, number];
}

export interface MotionTokens {
  duration: MotionDurations;
  easing: MotionEasing;
  /** Beautiful UI's `active:scale-[0.96]` control press feedback. */
  pressScale: number;
}

// Beautiful UI motion (plan §10.2): durations 100/150/200/300/400ms, section
// entrance 600ms; signature easing `cubic-bezier(.23,1,.32,1)` plus
// `(.77,0,.175,1)` and the link ease `(.16,1,.3,1)`.
export const motion: MotionTokens = {
  duration: {
    instant: 0,
    fast: 100,
    base: 150,
    moderate: 200,
    slow: 300,
    slower: 400,
    entrance: 600,
  },
  easing: {
    standard: [0.23, 1, 0.32, 1],
    decelerate: [0.23, 1, 0.32, 1],
    accelerate: [0.77, 0, 0.175, 1],
    sharp: [0.16, 1, 0.3, 1],
    easeOutStrong: [0.23, 1, 0.32, 1],
    easeInOutStrong: [0.77, 0, 0.175, 1],
    link: [0.16, 1, 0.3, 1],
  },
  pressScale: 0.96,
};

/**
 * `prefers-reduced-motion` variant: every duration collapses to
 * (near-)instant while keeping linear easing, per plan §10.5. `pressScale`
 * is a discrete state, not an animated transition, so it is kept: reduced
 * motion removes the transition to it, not the state itself.
 */
export const reducedMotion: MotionTokens = {
  duration: {
    instant: 0,
    fast: 1,
    base: 1,
    moderate: 1,
    slow: 1,
    slower: 1,
    entrance: 1,
  },
  easing: {
    standard: [0, 0, 1, 1],
    decelerate: [0, 0, 1, 1],
    accelerate: [0, 0, 1, 1],
    sharp: [0, 0, 1, 1],
    easeOutStrong: [0, 0, 1, 1],
    easeInOutStrong: [0, 0, 1, 1],
    link: [0, 0, 1, 1],
  },
  pressScale: 0.96,
};

// ---------------------------------------------------------------------------
// Breakpoints
// ---------------------------------------------------------------------------

export interface BreakpointTokens {
  /** Minimum width, in CSS pixels, for the compact (single-column) layout. */
  compact: number;
  /** Minimum width, in CSS pixels, for the wide (multi-column) layout. */
  wide: number;
}

export const breakpoints: BreakpointTokens = {
  compact: 0,
  wide: 720,
};

// ---------------------------------------------------------------------------
// Themes
// ---------------------------------------------------------------------------

export type ColorScheme = "light" | "dark";

export interface ThemeTokens {
  scheme: ColorScheme;
  highContrast: boolean;
  colors: ColorTokens;
  typography: TypographyTokens;
  spacing: SpacingTokens;
  radii: RadiiTokens;
  elevation: ElevationTokens;
  /** Beautiful UI's ring-based shadow set (plan §10.2), per theme. */
  shadows: ShadowTokens;
  breakpoints: BreakpointTokens;
}

function buildTheme(
  scheme: ColorScheme,
  highContrast: boolean,
  colors: ColorTokens,
  shadows: ShadowTokens,
): ThemeTokens {
  return {
    scheme,
    highContrast,
    colors,
    typography,
    spacing,
    radii,
    elevation,
    shadows,
    breakpoints,
  };
}

export const lightTheme: ThemeTokens = buildTheme("light", false, lightColors, lightShadows);
export const darkTheme: ThemeTokens = buildTheme("dark", false, darkColors, darkShadows);
export const lightHighContrastTheme: ThemeTokens = buildTheme(
  "light",
  true,
  lightHighContrastColors,
  lightShadows,
);
export const darkHighContrastTheme: ThemeTokens = buildTheme(
  "dark",
  true,
  darkHighContrastColors,
  darkShadows,
);

export const themes: Record<ColorScheme, { normal: ThemeTokens; highContrast: ThemeTokens }> = {
  light: { normal: lightTheme, highContrast: lightHighContrastTheme },
  dark: { normal: darkTheme, highContrast: darkHighContrastTheme },
};

/**
 * Accessibility hook: resolve the correct theme object for a color scheme
 * and a `prefers-contrast: more` / high-contrast platform setting. Plain
 * function (not a React hook) so it stays usable from `frontend-core`,
 * web, and Android alike.
 */
export function resolveTheme(scheme: ColorScheme, highContrast: boolean): ThemeTokens {
  return highContrast ? themes[scheme].highContrast : themes[scheme].normal;
}

/**
 * Accessibility hook: resolve the correct motion tokens for a
 * `prefers-reduced-motion` platform setting.
 */
export function resolveMotion(reduceMotion: boolean): MotionTokens {
  return reduceMotion ? reducedMotion : motion;
}
