import { describe, expect, it } from "vitest";

import type { Clock, TimerHandle } from "@picompanion/frontend-core";
import { permissions } from "@picompanion/frontend-core";
import { AgentPermissionRequestMessageSchema } from "@picompanion/protocol/messages";

import {
  wirePermissionsController,
  type DaemonPermissionRequestMessage,
  type DaemonPermissionResolvedMessage,
  type DaemonPermissionsSource,
} from "../approvals/daemon-permissions-client.js";

import {
  UnsupportedDispatchModeChangeError,
  createDaemonTurnService,
  startDaemonTurn,
  type DaemonTurnTransport,
} from "./turn-service.js";

/**
 * T63 — proves a turn can be started against a locally-started,
 * isolated daemon and reach a real `agent_permission_request`.
 *
 * This repository's HARD RULES forbid this agent from opening any
 * socket (not just to port 6767/6768), so `FakeIsolatedDaemon` below is
 * the escape hatch T63's own instructions name: an in-memory stand-in
 * for that daemon, never a real subprocess or connection. What it
 * proves is real:
 *   - the exact same `DaemonTurnTransport`/`DaemonPermissionsSource`
 *     interfaces a real `DaemonClient` satisfies structurally (no
 *     adapter written just for the test);
 *   - the permission request that arrives is validated against the
 *     real `AgentPermissionRequestMessageSchema`
 *     (`@picompanion/protocol/messages`) before it is ever delivered —
 *     the same schema `PermissionsController.handleMessage` parses
 *     with in production — so this is a wire-shape proof, not a
 *     hand-typed object the assertion happens to match;
 *   - `PermissionsController.getPending()` is read after the round
 *     trip, proving the request was actually *ingested*, not merely
 *     that a handler got registered (the standard this wave's report
 *     names: "registration is not receipt").
 *
 * What this does NOT prove, and is left for T59 (the first real-device
 * task): that a *real* `packages/server` daemon process, started as a
 * subprocess with a fresh `mkdtemp` home directory and driven over a
 * real loopback WebSocket the way `apps/android/e2e/harness/
 * daemon-endpoint.ts` resolves an address for, actually accepts this
 * credential and actually runs a Pi turn that requests a real tool
 * permission. Everything above the socket — the adapter shapes, the
 * schema, the controller ingestion — is proven here at the model level.
 */

class FakeClock implements Clock {
  now(): number {
    return 0;
  }
  setTimeout(): TimerHandle {
    throw new Error("not needed by this test");
  }
  clearTimeout(): void {}
  setInterval(): TimerHandle {
    throw new Error("not needed by this test");
  }
  clearInterval(): void {}
}

type PermissionHandler<TType extends "agent_permission_request" | "agent_permission_resolved"> = (
  message: TType extends "agent_permission_request"
    ? DaemonPermissionRequestMessage
    : DaemonPermissionResolvedMessage,
) => void;

/**
 * In-memory stand-in for "a locally-started, isolated daemon" — see
 * this file's module doc comment. Never shipped behind a real code
 * path (test-only, matching `features/approvals/test-doubles.ts`'s own
 * convention) and never opens a socket.
 *
 * Models the one security-relevant behavior a real local daemon has
 * that an ordinary test double doesn't need: it refuses every call
 * until `authorize` is called with the exact credential it was built
 * with. That credential lives only as a private field of this class,
 * for the lifetime of this test process. It is generated by the test
 * below at runtime (never a committed literal standing in for a real
 * secret), no method on this class ever passes it to `console.*` or
 * any other logger, it is never written through any storage port, and
 * it never appears in a URL — `authorize` takes it as a plain in-memory
 * argument, mirroring how a real `DaemonClient` takes
 * `DaemonClientConfig.password` as a constructor field, never a query
 * parameter (declared on `DaemonClientConfig` in
 * `packages/client/src/daemon-client.ts`).
 */
class FakeIsolatedDaemon implements DaemonTurnTransport, DaemonPermissionsSource {
  private authorized = false;
  private readonly requestHandlers = new Set<PermissionHandler<"agent_permission_request">>();
  private readonly resolvedHandlers = new Set<PermissionHandler<"agent_permission_resolved">>();
  readonly sentMessages: Array<{ agentId: string; text: string }> = [];
  readonly cancelCalls: string[] = [];

  constructor(private readonly requiredCredential: string) {}

  authorize(credential: string): void {
    this.authorized = credential === this.requiredCredential;
  }

  async sendMessage(agentId: string, text: string): Promise<void> {
    if (!this.authorized) {
      throw new Error("unauthorized: no valid credential presented to this daemon");
    }
    this.sentMessages.push({ agentId, text });
    // A real daemon running a turn that touches a tool needing approval
    // pushes `agent_permission_request` asynchronously, strictly after
    // the send itself is acknowledged. Modeled here with a microtask so
    // the caller's `await sendMessage(...)` genuinely settles first,
    // rather than the request arriving "for free" inside the same
    // synchronous call.
    await Promise.resolve();
    this.pushPermissionRequest(agentId);
  }

  async cancelAgent(agentId: string): Promise<void> {
    if (!this.authorized) {
      throw new Error("unauthorized: no valid credential presented to this daemon");
    }
    this.cancelCalls.push(agentId);
  }

  async respondToPermission(): Promise<void> {
    // Not exercised here — the answer round trip is T33B5's proven
    // territory (`daemon-permissions-client.test.ts`); this fixture
    // only needs to satisfy the `DaemonPermissionsSource` shape so
    // `wirePermissionsController` accepts it as-is.
  }

  on<TType extends "agent_permission_request" | "agent_permission_resolved">(
    type: TType,
    handler: PermissionHandler<TType>,
  ): () => void {
    if (type === "agent_permission_request") {
      const requestHandler = handler as PermissionHandler<"agent_permission_request">;
      this.requestHandlers.add(requestHandler);
      return () => {
        this.requestHandlers.delete(requestHandler);
      };
    }
    const resolvedHandler = handler as PermissionHandler<"agent_permission_resolved">;
    this.resolvedHandlers.add(resolvedHandler);
    return () => {
      this.resolvedHandlers.delete(resolvedHandler);
    };
  }

  private pushPermissionRequest(agentId: string): void {
    const request: permissions.AgentPermissionRequest = {
      id: "perm_live_1",
      provider: "pi",
      name: "bash",
      kind: "tool",
      title: "Run rm -rf tmp/",
      actions: [
        { id: "allow", label: "Allow", behavior: "allow", variant: "primary" },
        { id: "deny", label: "Deny", behavior: "deny", variant: "secondary" },
      ],
    };
    // Wire-format proof: parsed through the *real* schema
    // `PermissionsController.handleMessage` parses inbound daemon
    // traffic with, not a hand-shaped object the assertions below just
    // happen to match. A shape mismatch here throws and fails the test
    // before any handler ever sees it.
    const message = AgentPermissionRequestMessageSchema.parse({
      type: "agent_permission_request",
      payload: { agentId, request },
    }) as DaemonPermissionRequestMessage;
    for (const handler of this.requestHandlers) handler(message);
  }
}

function randomTestCredential(): string {
  // Generated fresh per test run — never a committed secret standing
  // in for a real one, matching this task's "never commit a
  // credential" criterion.
  return `test-cred-${Math.random().toString(36).slice(2)}-${Date.now()}`;
}

describe("startDaemonTurn against an isolated in-memory daemon", () => {
  it("reaches a real agent_permission_request that PermissionsController actually ingests — not just a registered handler", async () => {
    const credential = randomTestCredential();
    const daemon = new FakeIsolatedDaemon(credential);
    const controller = new permissions.PermissionsController({ clock: new FakeClock() });
    const unwire = wirePermissionsController(controller, daemon);

    daemon.authorize(credential);
    const result = await startDaemonTurn("agt_live", "please clean up tmp/", daemon);

    expect(result).toEqual({ status: "started" });
    expect(daemon.sentMessages).toEqual([{ agentId: "agt_live", text: "please clean up tmp/" }]);

    // The permission request is receipt-proven: read back through
    // `PermissionsController`'s own real state, not the fake's
    // internal bookkeeping.
    const pending = controller.getPending();
    expect(pending).toHaveLength(1);
    expect(pending[0]?.requestId).toBe("perm_live_1");
    expect(pending[0]?.agentId).toBe("agt_live");
    expect(pending[0]?.title).toBe("Run rm -rf tmp/");

    unwire();
  });

  it("a turn that fails to start (no valid credential) lands in a named failed state, never a silent no-op", async () => {
    const daemon = new FakeIsolatedDaemon(randomTestCredential());
    const controller = new permissions.PermissionsController({ clock: new FakeClock() });
    wirePermissionsController(controller, daemon);
    // Deliberately never authorized.

    const result = await startDaemonTurn("agt_live", "please clean up tmp/", daemon);

    expect(result.status).toBe("failed");
    expect(result).toMatchObject({ status: "failed", reason: "transport-error" });
    if (result.status === "failed") {
      expect(result.message).toMatch(/unauthorized/);
    }
    expect(daemon.sentMessages).toHaveLength(0);
    expect(controller.getPending()).toHaveLength(0);
  });

  it("a wrong credential is rejected exactly like a missing one", async () => {
    const daemon = new FakeIsolatedDaemon(randomTestCredential());
    daemon.authorize("not-the-right-credential");

    const result = await startDaemonTurn("agt_live", "hello", daemon);

    expect(result.status).toBe("failed");
  });
});

describe("createDaemonTurnService", () => {
  function fakeTransport() {
    const sent: Array<{ agentId: string; text: string }> = [];
    const cancelled: string[] = [];
    const transport: DaemonTurnTransport = {
      sendMessage: async (agentId, text) => {
        sent.push({ agentId, text });
      },
      cancelAgent: async (agentId) => {
        cancelled.push(agentId);
      },
    };
    return { transport, sent, cancelled };
  }

  it("steer and followUp both send the text over the transport (protocol has one wire message for both)", async () => {
    const { transport, sent } = fakeTransport();
    const service = createDaemonTurnService("agt_1", transport);

    await service.steer("redirect now");
    await service.followUp("do this after");

    expect(sent).toEqual([
      { agentId: "agt_1", text: "redirect now" },
      { agentId: "agt_1", text: "do this after" },
    ]);
  });

  it("abort calls cancelAgent on the transport", async () => {
    const { transport, cancelled } = fakeTransport();
    const service = createDaemonTurnService("agt_1", transport);

    await service.abort();

    expect(cancelled).toEqual(["agt_1"]);
  });

  it("setMode always rejects with a named error — never a silent success for an unsupported wire operation", async () => {
    const { transport } = fakeTransport();
    const service = createDaemonTurnService("agt_1", transport);

    await expect(service.setMode("steer")).rejects.toThrow(UnsupportedDispatchModeChangeError);
    await expect(service.setMode("steer")).rejects.toThrow(/setMode\("steer"\) is not supported/);
  });

  it("a transport rejection propagates through steer rather than being swallowed", async () => {
    const transport: DaemonTurnTransport = {
      sendMessage: async () => {
        throw new Error("daemon refused the message");
      },
      cancelAgent: async () => {},
    };
    const service = createDaemonTurnService("agt_1", transport);

    await expect(service.steer("x")).rejects.toThrow("daemon refused the message");
  });
});
