/**
 * T31A's required smoke scenario: "connect to an isolated daemon"
 * (plan.md §14.3's first bullet). Drives the real `/connect` screen —
 * `ConnectFormContainer` -> `ConnectForm` -> `attempt-host-connection.ts`
 * / `authenticate-host.ts` — against the real, isolated daemon
 * `global-setup.ts` started for this run, over a real browser and a
 * real static production build. Nothing here is mocked: a passing run
 * proves the harness (isolated daemon fixture, static build/preview
 * server, and the port-6767 guard) actually works end to end.
 */
import { expect, test } from "./fixtures/test.js";

test.describe("connect to an isolated daemon", () => {
  test("reaches the isolated daemon and persists the connection", async ({
    page,
    daemonConnection,
  }) => {
    await page.goto(`${daemonConnection.webBaseUrl}/connect`);

    // T54A2 added the shell's single visually-hidden `<h1>`, which on this
    // route reads "Connect to a host". Playwright's `name` is a
    // case-insensitive SUBSTRING match unless `exact` is set, so the bare
    // name below now also matches that `<h1>`. `exact: true` pins this back
    // to the screen's own `<h2>Connect</h2>` -- a tightening, not a
    // loosening: it asserts one specific element instead of "any heading
    // whose name contains Connect".
    await expect(page.getByRole("heading", { name: "Connect", exact: true })).toBeVisible();

    await page.getByLabel("Host label").fill("E2E Daemon");
    await page.getByLabel("Host address").fill(daemonConnection.address);
    await page.getByRole("button", { name: "Connect", exact: true }).click();

    // CORRECTED (FIX-CI9): this used to assert the `connect-status-banner`
    // reads "Reached E2E Daemon", carries `role="status"`, and is followed by
    // a visible "Forget saved credentials" button. A successful connect now
    // lands the user on that host's session list — `ConnectForm` sets that
    // status message and calls `onConnected` in the same tick — so the banner
    // is never painted and none of those three could be observed.
    //
    // The destination is the success signal. The saved profile id is
    // generated by `hosts.HostProfileStore`, not chosen here, so the segment
    // is matched rather than named.
    await page.waitForURL(/\/h\/[^/]+\/sessions$/, { timeout: 15_000 });
    await expect(page.getByRole("heading", { level: 1, name: "Session list" })).toBeVisible();

    // The persistence proof this scenario exists to give (T27A2: the round
    // trip went through `hosts.HostProfileStore`, not just a probe) is now
    // made by a COLD, non-SPA reload of the landed route: nothing but a
    // persisted profile can make `DaemonClientProvider`'s initial-connect
    // effect re-establish the connection and re-render the list. That is a
    // stronger claim than the "Forget saved credentials" affordance it
    // replaces, which only proved the id was still in component state.
    await page.reload();
    await expect(page.getByRole("heading", { level: 1, name: "Session list" })).toBeVisible({
      timeout: 15_000,
    });
  });
});
