/**
 * Android's real terminal host (T32S11) — the RN/`react-native-webview` half
 * of the WebView terminal whose RN-free protocol half lives in
 * `./terminal-webview-port.ts`. Deliberately thin, in the same
 * un-`vitest`-provable shape as `terminal-screen.tsx` and `QrPairingPanel.tsx`:
 * every decision worth proving is in `terminal-session-controller.ts` and
 * `terminal-webview-port.ts`, and this file only renders one `<WebView>` and
 * binds it to the port.
 *
 * The page itself is `./terminal-webview-html.gen.ts`, a committed xterm.js
 * bundle generated by `../../scripts/build-terminal-webview-html.mjs` (see
 * that file's header for how to regenerate it). See the port's doc comment
 * for the JSON protocol between the two.
 */
import { useCallback, useRef } from "react";
import { WebView } from "react-native-webview";

import { terminalWebViewHtml } from "./terminal-webview-html.gen.js";
import type { TerminalWebViewPort } from "./terminal-webview-port.js";

/**
 * The imperative surface `react-native-webview` exposes on its ref. Its own
 * `.d.ts` types the Android ref as `{}`, so this is the narrowest local
 * shape the binding actually needs — not a broad cast to `any`.
 */
interface WebViewHandle {
  postMessage(data: string): void;
}

export interface TerminalWebViewHostProps {
  port: TerminalWebViewPort;
  testId?: string;
}

export function TerminalWebViewHost({ port, testId }: TerminalWebViewHostProps) {
  const handleRef = useRef<WebViewHandle | null>(null);

  const bindPort = useCallback(
    (instance: unknown) => {
      if (!instance) {
        handleRef.current = null;
        return;
      }
      const handle = instance as WebViewHandle;
      handleRef.current = handle;
      port.attachHost?.({
        postMessage: (data) => handle.postMessage(data),
      });
    },
    [port],
  );

  return (
    <WebView
      ref={bindPort}
      testID={testId}
      originWhitelist={["*"]}
      source={{ html: terminalWebViewHtml }}
      onMessage={(event) => port.handleHostMessage?.(event.nativeEvent.data)}
      scrollEnabled={false}
      overScrollMode="never"
      setSupportMultipleWindows={false}
      style={styles.webview}
    />
  );
}

const styles = {
  webview: { flex: 1, backgroundColor: "transparent" },
} as const;
